[project]
name = "fly-in"
version = "0.1.0"
description = "42 project"
authors = [
    {name = "srosu", email = "srosu@student.42belgium.be"}
]
requires-python = ">=3.10"
dependencies = [
    "pydantic >= 2.13.4",
    "pygame >= 2.6.1"
]

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry]
package-mode = false