[project]
name = "fly-in"
version = "0.1.0"
description = "42 project"
authors = [
    {name = "srosu", email = "srosu@student.42belgium.be"}
]
requires-python = ">=3.10"
dependencies = [
    "pydantic >= 2.13.4",
    "pygame >= 2.6.1",
    "mypy (>=2.3.1,<3.0.0)",
    "flake8 (>=7.3.0,<8.0.0)"
]

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry]
package-mode = false